// Static translation table: German country names -> ISO 3166-1 alpha-2 codes
// This table never changes

export const COUNTRY_CODES: Record<string, string> = {
  // German names
  'deutschland': 'DE',
  'germany': 'DE',
  'österreich': 'AT',
  'oesterreich': 'AT',
  'austria': 'AT',
  'schweiz': 'CH',
  'switzerland': 'CH',
  'frankreich': 'FR',
  'france': 'FR',
  'italien': 'IT',
  'italy': 'IT',
  'spanien': 'ES',
  'spain': 'ES',
  'portugal': 'PT',
  'niederlande': 'NL',
  'netherlands': 'NL',
  'holland': 'NL',
  'belgien': 'BE',
  'belgium': 'BE',
  'luxemburg': 'LU',
  'luxembourg': 'LU',
  'polen': 'PL',
  'poland': 'PL',
  'tschechien': 'CZ',
  'tschechische republik': 'CZ',
  'czech republic': 'CZ',
  'czechia': 'CZ',
  'slowakei': 'SK',
  'slovakia': 'SK',
  'ungarn': 'HU',
  'hungary': 'HU',
  'rumänien': 'RO',
  'rumaenien': 'RO',
  'romania': 'RO',
  'bulgarien': 'BG',
  'bulgaria': 'BG',
  'griechenland': 'GR',
  'greece': 'GR',
  'türkei': 'TR',
  'tuerkei': 'TR',
  'turkey': 'TR',
  'dänemark': 'DK',
  'daenemark': 'DK',
  'denmark': 'DK',
  'schweden': 'SE',
  'sweden': 'SE',
  'norwegen': 'NO',
  'norway': 'NO',
  'finnland': 'FI',
  'finland': 'FI',
  'estland': 'EE',
  'estonia': 'EE',
  'lettland': 'LV',
  'latvia': 'LV',
  'litauen': 'LT',
  'lithuania': 'LT',
  'irland': 'IE',
  'ireland': 'IE',
  'großbritannien': 'GB',
  'grossbritannien': 'GB',
  'vereinigtes königreich': 'GB',
  'vereinigtes koenigreich': 'GB',
  'united kingdom': 'GB',
  'uk': 'GB',
  'england': 'GB',
  'slowenien': 'SI',
  'slovenia': 'SI',
  'kroatien': 'HR',
  'croatia': 'HR',
  'serbien': 'RS',
  'serbia': 'RS',
  'bosnien': 'BA',
  'bosnien und herzegowina': 'BA',
  'bosnia': 'BA',
  'montenegro': 'ME',
  'nordmazedonien': 'MK',
  'north macedonia': 'MK',
  'albanien': 'AL',
  'albania': 'AL',
  'kosovo': 'XK',
  'moldau': 'MD',
  'moldawien': 'MD',
  'moldova': 'MD',
  'ukraine': 'UA',
  'weißrussland': 'BY',
  'weissrussland': 'BY',
  'belarus': 'BY',
  'russland': 'RU',
  'russia': 'RU',
  'island': 'IS',
  'iceland': 'IS',
  'malta': 'MT',
  'zypern': 'CY',
  'cyprus': 'CY',
  'andorra': 'AD',
  'monaco': 'MC',
  'san marino': 'SM',
  'vatikanstadt': 'VA',
  'vatican': 'VA',
  'liechtenstein': 'LI',
  // Common non-European destinations
  'usa': 'US',
  'vereinigte staaten': 'US',
  'united states': 'US',
  'amerika': 'US',
  'kanada': 'CA',
  'canada': 'CA',
  'mexiko': 'MX',
  'mexico': 'MX',
  'brasilien': 'BR',
  'brazil': 'BR',
  'argentinien': 'AR',
  'argentina': 'AR',
  'chile': 'CL',
  'australien': 'AU',
  'australia': 'AU',
  'neuseeland': 'NZ',
  'new zealand': 'NZ',
  'japan': 'JP',
  'china': 'CN',
  'südkorea': 'KR',
  'suedkorea': 'KR',
  'south korea': 'KR',
  'korea': 'KR',
  'indien': 'IN',
  'india': 'IN',
  'singapur': 'SG',
  'singapore': 'SG',
  'thailand': 'TH',
  'vietnam': 'VN',
  'indonesien': 'ID',
  'indonesia': 'ID',
  'malaysia': 'MY',
  'philippinen': 'PH',
  'philippines': 'PH',
  'südafrika': 'ZA',
  'suedafrika': 'ZA',
  'south africa': 'ZA',
  'ägypten': 'EG',
  'aegypten': 'EG',
  'egypt': 'EG',
  'marokko': 'MA',
  'morocco': 'MA',
  'tunesien': 'TN',
  'tunisia': 'TN',
  'israel': 'IL',
  'vereinigte arabische emirate': 'AE',
  'vae': 'AE',
  'uae': 'AE',
  'dubai': 'AE',
  'saudi-arabien': 'SA',
  'saudi arabien': 'SA',
  'saudi arabia': 'SA',
};

export function getCountryCode(countryName: string): string | null {
  const normalized = countryName.toLowerCase().trim();
  return COUNTRY_CODES[normalized] || null;
}

export function extractCountryFromAddress(address: string): { country: string | null; isoCode: string | null } {
  const lines = address.split('\n').map(l => l.trim()).filter(Boolean);
  if (lines.length === 0) return { country: null, isoCode: null };
  
  // Last non-empty line is typically the country
  const lastLine = lines[lines.length - 1];
  const isoCode = getCountryCode(lastLine);
  
  return { country: lastLine, isoCode };
}
